name: Django App Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install pm2
        run: npm install pm2@latest -g

      - name: Create virtual environment
        run: python -m venv venv

      - name: Install dependencies in virtual environment
        run: source venv/bin/activate && pip install -r requirements.txt

      - name: Run migrations
        run: source venv/bin/activate && python manage.py migrate

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Start App with pm2
        run: |
          source venv/bin/activate
          pm2 start "python manage.py runserver"

      - name: Save pm2 config
        run: pm2 save
