name: Django App Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Update ubuntu repos with curl installation
        run: sudo apt update -y && sudo apt install -y curl

      - name: Install python3 and pip3
        run: sudo apt install -y python3.11 python3-pip

      - name: Install NodeJS
        run: cd ~ && curl -sL https://deb.nodesource.com/setup_18.x -o /tmp/nodesource_setup.sh && sudo bash /tmp/nodesource_setup.sh && sudo apt install -y nodejs

      - name: Install pm2
        run: sudo npm install pm2@latest -g

      - name: Install depenendencies
        run: pip install -r requirements.txt

      - name: Run migrations
        run: python3 manage.py migrate

  deploy:
    steps:
      - name: Start App with pm2
        run: pm2 start "python3 manage.py runserver"

      - name: Save pm2 config
        run: pm2 save